/*
 * Copyright 2021 Canopy Pte Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default {
  meta: { total_pages: 1, page: 1, per_page: 1000, total: 240 },
  consolidated_holdings: [
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 984,
      ticker: "AAPL_US",
      security_name: "Apple Inc",
      isin: null,
      ccyaccountid: 4882,
      contract_currency: "USD",
      quantity: 100.0,
      latest_price_date: "2020-10-27",
      latest_price_close: 116.6,
      latest_price_clean: null,
      market_value_usd: 11660.0,
      absolute_market_value_usd: 11660.0,
      mtm_total_usd: -2556.999999999999,
      mtm_price_usd: -2556.999999999999,
      mtm_fx_usd: null,
      mtm_accrued_usd: null,
      user_asset_class: "Equities",
      user_industry: "Computers",
      user_geography: "United States of America",
      canopy_asset_class: "Equity_DM_Listed_US",
      canopy_geography: "United States of America",
      partner_asset_class: null,
      partner_industry: null,
      partner_geography: null,
      credit_rating: null,
      em_dm: "DM",
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 11660.0,
      absolute_market_value_base_ccy: 11660.0,
      mtm_total_base_ccy: -2556.999999999999,
      mtm_price_base_ccy: -2556.999999999999,
      mtm_fx_base_ccy: null,
      mtm_accrued_base_ccy: null,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "bb8c3cea-c3a8-4fc0-8a1c-3f133927ce93",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 0,
      ticker: "Cash",
      security_name: "Cash",
      isin: null,
      ccyaccountid: 17719,
      contract_currency: "CAD",
      quantity: 7880.0,
      latest_price_date: null,
      latest_price_close: null,
      latest_price_clean: null,
      market_value_usd: 5991.951999999999,
      absolute_market_value_usd: 5991.951999999999,
      mtm_total_usd: 0.0,
      mtm_price_usd: 0.0,
      mtm_fx_usd: 0.0,
      mtm_accrued_usd: 0.0,
      user_asset_class: "Cash",
      user_industry: "Cash",
      user_geography: "Cash",
      canopy_asset_class: "Cash",
      canopy_geography: "Cash",
      partner_asset_class: "Cash",
      partner_industry: "Cash",
      partner_geography: "Cash",
      credit_rating: null,
      em_dm: null,
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 5991.951999999999,
      absolute_market_value_base_ccy: 5991.951999999999,
      mtm_total_base_ccy: 0.0,
      mtm_price_base_ccy: 0.0,
      mtm_fx_base_ccy: 0.0,
      mtm_accrued_base_ccy: 0.0,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "7b5b14d3-2d00-45f7-89af-0223606be8f9",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 984,
      ticker: "AAPL_US",
      security_name: "Apple Inc",
      isin: null,
      ccyaccountid: 4882,
      contract_currency: "USD",
      quantity: 100.0,
      latest_price_date: "2020-10-27",
      latest_price_close: 116.6,
      latest_price_clean: null,
      market_value_usd: 11660.0,
      absolute_market_value_usd: 11660.0,
      mtm_total_usd: -2556.999999999999,
      mtm_price_usd: -2556.999999999999,
      mtm_fx_usd: null,
      mtm_accrued_usd: null,
      user_asset_class: "Equities",
      user_industry: "Computers",
      user_geography: "United States of America",
      canopy_asset_class: "Equity_DM_Listed_US",
      canopy_geography: "United States of America",
      partner_asset_class: null,
      partner_industry: null,
      partner_geography: null,
      credit_rating: null,
      em_dm: "DM",
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 11660.0,
      absolute_market_value_base_ccy: 11660.0,
      mtm_total_base_ccy: -2556.999999999999,
      mtm_price_base_ccy: -2556.999999999999,
      mtm_fx_base_ccy: null,
      mtm_accrued_base_ccy: null,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "bb8c3cea-c3a8-4fc0-8a1c-3f133927ce93",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 0,
      ticker: "Cash",
      security_name: "Cash",
      isin: null,
      ccyaccountid: 17719,
      contract_currency: "CAD",
      quantity: 7880.0,
      latest_price_date: null,
      latest_price_close: null,
      latest_price_clean: null,
      market_value_usd: 5991.951999999999,
      absolute_market_value_usd: 5991.951999999999,
      mtm_total_usd: 0.0,
      mtm_price_usd: 0.0,
      mtm_fx_usd: 0.0,
      mtm_accrued_usd: 0.0,
      user_asset_class: "Cash",
      user_industry: "Cash",
      user_geography: "Cash",
      canopy_asset_class: "Cash",
      canopy_geography: "Cash",
      partner_asset_class: "Cash",
      partner_industry: "Cash",
      partner_geography: "Cash",
      credit_rating: null,
      em_dm: null,
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 5991.951999999999,
      absolute_market_value_base_ccy: 5991.951999999999,
      mtm_total_base_ccy: 0.0,
      mtm_price_base_ccy: 0.0,
      mtm_fx_base_ccy: 0.0,
      mtm_accrued_base_ccy: 0.0,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "7b5b14d3-2d00-45f7-89af-0223606be8f9",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 984,
      ticker: "AAPL_US",
      security_name: "Apple Inc",
      isin: null,
      ccyaccountid: 4882,
      contract_currency: "USD",
      quantity: 100.0,
      latest_price_date: "2020-10-27",
      latest_price_close: 116.6,
      latest_price_clean: null,
      market_value_usd: 11660.0,
      absolute_market_value_usd: 11660.0,
      mtm_total_usd: -2556.999999999999,
      mtm_price_usd: -2556.999999999999,
      mtm_fx_usd: null,
      mtm_accrued_usd: null,
      user_asset_class: "Equities",
      user_industry: "Computers",
      user_geography: "United States of America",
      canopy_asset_class: "Equity_DM_Listed_US",
      canopy_geography: "United States of America",
      partner_asset_class: null,
      partner_industry: null,
      partner_geography: null,
      credit_rating: null,
      em_dm: "DM",
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 11660.0,
      absolute_market_value_base_ccy: 11660.0,
      mtm_total_base_ccy: -2556.999999999999,
      mtm_price_base_ccy: -2556.999999999999,
      mtm_fx_base_ccy: null,
      mtm_accrued_base_ccy: null,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "bb8c3cea-c3a8-4fc0-8a1c-3f133927ce93",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 0,
      ticker: "Cash",
      security_name: "Cash",
      isin: null,
      ccyaccountid: 17719,
      contract_currency: "CAD",
      quantity: 7880.0,
      latest_price_date: null,
      latest_price_close: null,
      latest_price_clean: null,
      market_value_usd: 5991.951999999999,
      absolute_market_value_usd: 5991.951999999999,
      mtm_total_usd: 0.0,
      mtm_price_usd: 0.0,
      mtm_fx_usd: 0.0,
      mtm_accrued_usd: 0.0,
      user_asset_class: "Cash",
      user_industry: "Cash",
      user_geography: "Cash",
      canopy_asset_class: "Cash",
      canopy_geography: "Cash",
      partner_asset_class: "Cash",
      partner_industry: "Cash",
      partner_geography: "Cash",
      credit_rating: null,
      em_dm: null,
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 5991.951999999999,
      absolute_market_value_base_ccy: 5991.951999999999,
      mtm_total_base_ccy: 0.0,
      mtm_price_base_ccy: 0.0,
      mtm_fx_base_ccy: 0.0,
      mtm_accrued_base_ccy: 0.0,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "7b5b14d3-2d00-45f7-89af-0223606be8f9",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 11887,
      ticker: "ESZ4",
      security_name: "E-mini S&P 500 Futures - Dec 2014",
      isin: null,
      ccyaccountid: 4882,
      contract_currency: "USD",
      quantity: 10.0,
      latest_price_date: "2017-07-03",
      latest_price_close: 200.0,
      latest_price_clean: null,
      market_value_usd: 2000.0,
      absolute_market_value_usd: 2000.0,
      mtm_total_usd: 0.0,
      mtm_price_usd: 0.0,
      mtm_fx_usd: null,
      mtm_accrued_usd: null,
      user_asset_class: "Derivative",
      user_industry: "Derivative",
      user_geography: "Derivative",
      canopy_asset_class: "Derivative",
      canopy_geography: null,
      partner_asset_class: null,
      partner_industry: null,
      partner_geography: null,
      credit_rating: null,
      em_dm: null,
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 2000.0,
      absolute_market_value_base_ccy: 2000.0,
      mtm_total_base_ccy: 0.0,
      mtm_price_base_ccy: 0.0,
      mtm_fx_base_ccy: null,
      mtm_accrued_base_ccy: null,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "03e2f5bd-421f-46a0-bdc3-912317161eb6",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 142,
      ticker: "FIDAAAA_LX",
      security_name: "Fidelity Funds-Amer-Ausd Acc",
      isin: null,
      ccyaccountid: 4882,
      contract_currency: "USD",
      quantity: 100.0,
      latest_price_date: "2020-10-27",
      latest_price_close: 21.71,
      latest_price_clean: null,
      market_value_usd: 2171.0,
      absolute_market_value_usd: 2171.0,
      mtm_total_usd: -44.99999999999993,
      mtm_price_usd: -44.99999999999993,
      mtm_fx_usd: null,
      mtm_accrued_usd: null,
      user_asset_class: "Funds",
      user_industry: null,
      user_geography: "U.S.",
      canopy_asset_class: "Fund_Equity",
      canopy_geography: "U.S.",
      partner_asset_class: null,
      partner_industry: null,
      partner_geography: null,
      credit_rating: null,
      em_dm: "DM",
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 2171.0,
      absolute_market_value_base_ccy: 2171.0,
      mtm_total_base_ccy: -44.99999999999993,
      mtm_price_base_ccy: -44.99999999999993,
      mtm_fx_base_ccy: null,
      mtm_accrued_base_ccy: null,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "f726b13c-d8d7-43e0-8a7f-139a16aff640",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 3268,
      ticker: "GOOG_US",
      security_name: "Alphabet Inc-Cl C",
      isin: null,
      ccyaccountid: 4882,
      contract_currency: "USD",
      quantity: 1.0,
      latest_price_date: "2020-10-27",
      latest_price_close: 1604.26,
      latest_price_clean: null,
      market_value_usd: 1604.26,
      absolute_market_value_usd: 1604.26,
      mtm_total_usd: 524.26,
      mtm_price_usd: 524.26,
      mtm_fx_usd: null,
      mtm_accrued_usd: null,
      user_asset_class: "Equities",
      user_industry: "Internet",
      user_geography: "United States of America",
      canopy_asset_class: "Equity_DM_Listed_US",
      canopy_geography: "United States of America",
      partner_asset_class: null,
      partner_industry: null,
      partner_geography: null,
      credit_rating: null,
      em_dm: "DM",
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 1604.26,
      absolute_market_value_base_ccy: 1604.26,
      mtm_total_base_ccy: 524.26,
      mtm_price_base_ccy: 524.26,
      mtm_fx_base_ccy: null,
      mtm_accrued_base_ccy: null,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "eb63612c-34f9-43e8-aac3-ccb5d2d6a3b2",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 874,
      ticker: "HACK_US",
      security_name: "Etfmg Prime Cyber Security E",
      isin: null,
      ccyaccountid: 4882,
      contract_currency: "USD",
      quantity: 100.0,
      latest_price_date: "2020-10-27",
      latest_price_close: 47.5,
      latest_price_clean: null,
      market_value_usd: 4750.0,
      absolute_market_value_usd: 4750.0,
      mtm_total_usd: 1698.9999999999998,
      mtm_price_usd: 1698.9999999999998,
      mtm_fx_usd: null,
      mtm_accrued_usd: null,
      user_asset_class: "Funds",
      user_industry: null,
      user_geography: "Global",
      canopy_asset_class: "Fund_Equity",
      canopy_geography: "Global",
      partner_asset_class: null,
      partner_industry: null,
      partner_geography: null,
      credit_rating: null,
      em_dm: "DM",
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 4750.0,
      absolute_market_value_base_ccy: 4750.0,
      mtm_total_base_ccy: 1698.9999999999998,
      mtm_price_base_ccy: 1698.9999999999998,
      mtm_fx_base_ccy: null,
      mtm_accrued_base_ccy: null,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "4487f97e-5075-492e-9c4a-994786072db2",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 35,
      ticker: "JPM_127990943",
      security_name:
        "CADUCEUS II BIOTECHNOLOGY OFFSHORE   LP                                                                                                            ",
      isin: null,
      ccyaccountid: 4882,
      contract_currency: "USD",
      quantity: 100.0,
      latest_price_date: "2017-06-12",
      latest_price_close: 12.0,
      latest_price_clean: null,
      market_value_usd: 1200.0,
      absolute_market_value_usd: 1200.0,
      mtm_total_usd: 1218.0,
      mtm_price_usd: 1218.0,
      mtm_fx_usd: null,
      mtm_accrued_usd: null,
      user_asset_class: "Others",
      user_industry: "others",
      user_geography: null,
      canopy_asset_class: "Others",
      canopy_geography: null,
      partner_asset_class: null,
      partner_industry: null,
      partner_geography: null,
      credit_rating: null,
      em_dm: "EM",
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 1200.0,
      absolute_market_value_base_ccy: 1200.0,
      mtm_total_base_ccy: 1218.0,
      mtm_price_base_ccy: 1218.0,
      mtm_fx_base_ccy: null,
      mtm_accrued_base_ccy: null,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "29ca9c15-27a2-4afe-a4c9-9dd9ad71d52c",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 45070,
      ticker: "Loan Create",
      security_name: "Loan Create",
      isin: null,
      ccyaccountid: 4882,
      contract_currency: "USD",
      quantity: -10000.0,
      latest_price_date: null,
      latest_price_close: 1.0,
      latest_price_clean: 1.0,
      market_value_usd: -10000.0,
      absolute_market_value_usd: 10000.0,
      mtm_total_usd: 0.0,
      mtm_price_usd: 0.0,
      mtm_fx_usd: 0.0,
      mtm_accrued_usd: 0.0,
      user_asset_class: "Loan",
      user_industry: "Loan",
      user_geography: "Loan",
      canopy_asset_class: "Loan",
      canopy_geography: null,
      partner_asset_class: "Loan",
      partner_industry: "Loan",
      partner_geography: "Loan",
      credit_rating: null,
      em_dm: null,
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: -10000.0,
      absolute_market_value_base_ccy: 10000.0,
      mtm_total_base_ccy: 0.0,
      mtm_price_base_ccy: 0.0,
      mtm_fx_base_ccy: 0.0,
      mtm_accrued_base_ccy: 0.0,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "1a59e786-0062-4787-9853-5854a8f74a5d",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 22182,
      ticker: "MM1382493686",
      security_name: "NOBLE GROUP LIMITED - RIGHTS",
      isin: null,
      ccyaccountid: 4884,
      contract_currency: "SGD",
      quantity: 100.0,
      latest_price_date: "2016-06-28",
      latest_price_close: 0.0,
      latest_price_clean: null,
      market_value_usd: 0.0,
      absolute_market_value_usd: 0.0,
      mtm_total_usd: -7359.0,
      mtm_price_usd: -7359.0,
      mtm_fx_usd: null,
      mtm_accrued_usd: null,
      user_asset_class: "Others",
      user_industry: "others",
      user_geography: "Hong Kong",
      canopy_asset_class: "Others",
      canopy_geography: "Hong Kong",
      partner_asset_class: null,
      partner_industry: null,
      partner_geography: null,
      credit_rating: null,
      em_dm: "DM",
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 0.0,
      absolute_market_value_base_ccy: 0.0,
      mtm_total_base_ccy: -7359.0,
      mtm_price_base_ccy: -7359.0,
      mtm_fx_base_ccy: null,
      mtm_accrued_base_ccy: null,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "fdc8d474-ff7a-4204-bf5a-7ac9a6e74e5b",
      history_date_text: "2020-10-27",
    },
    {
      history_date: "2020-10-27",
      parent_username: "aeolos",
      parent_user_id: 480,
      child_username: "aeolos-barcgb22-01",
      child_display_name: "aeolos-barcgb22-01",
      child_user_id: 2366,
      custodian_name: "Barclays Bank UK",
      counterparty_id: 177,
      security_id: 90,
      ticker: "MM1402131225",
      security_name: "MASS MUTUAL FINANCIAL GROUP LIFE POLICY NO. 83602988",
      isin: null,
      ccyaccountid: 4882,
      contract_currency: "USD",
      quantity: 1.0,
      latest_price_date: "2017-06-12",
      latest_price_close: 135000.0,
      latest_price_clean: null,
      market_value_usd: 135000.0,
      absolute_market_value_usd: 135000.0,
      mtm_total_usd: 35080.509999999995,
      mtm_price_usd: 35080.509999999995,
      mtm_fx_usd: null,
      mtm_accrued_usd: null,
      user_asset_class: "Insurance",
      user_industry: "insurance",
      user_geography: "United States of America",
      canopy_asset_class: "Insurance",
      canopy_geography: "United States of America",
      partner_asset_class: null,
      partner_industry: null,
      partner_geography: null,
      credit_rating: null,
      em_dm: "DM",
      bb_composite_rating: null,
      tags: null,
      market_value_base_ccy: 135000.0,
      absolute_market_value_base_ccy: 135000.0,
      mtm_total_base_ccy: 35080.509999999995,
      mtm_price_base_ccy: 35080.509999999995,
      mtm_fx_base_ccy: null,
      mtm_accrued_base_ccy: null,
      base_ccy: "USD",
      basefx_rate: null,
      created_at: "2020-10-29",
      uuid_key: "2b6f482f-b466-451a-90f7-a298a1b81f7b",
      history_date_text: "2020-10-27",
    },
  ],
};
